default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: zee_dog_github_development
  host: db
  username: postgres
  password: password


test:
  <<: *default
  database: zee_dog_github_test
  host: db
  username: postgres
  password: password


production:
  <<: *default
  database: zee_dog_github_production
  username: zee_dog
  password: <%= ENV['ZEE_DOG_GITHUB_DATABASE_PASSWORD'] %>